### ISSUE TITLE
Tipsy command not found

### ISSUE THREAD

**Issue by crazcalm** [withpulp/saucey#58]
The README states to run "bin/robo saucey:tipsy 'form firefox'", but tipsy seems to be an invalid command.
![screen shot 2015-05-11 at 11 42 13 am](https://cloud.githubusercontent.com/assets/3482344/7568894/5baecf2e-f7d3-11e4-9593-0dd073a009fa.png)

**Comment by sajjadhossain** [comment]
To be resolved by new robo methods
